HTTP error: 401 Client Error: Unauthorized for url: https://praktikum.yandex.ru/api/user_api/homework_statuses/?from_date=1622505600
Бот упал с ошибкой: 'NoneType' object has no attribute 'get'
Бот запущен
HTTP error: 401 Client Error: Unauthorized for url: https://praktikum.yandex.ru/api/user_api/homework_statuses/?from_date=1622505600
Бот упал с ошибкой: 'NoneType' object has no attribute 'get'
Бот запущен
HTTP error: 401 Client Error: Unauthorized for url: https://praktikum.yandex.ru/api/user_api/homework_statuses/?from_date=1622505600
Бот упал с ошибкой: 'NoneType' object has no attribute 'get'
Бот запущен
HTTP error: 401 Client Error: Unauthorized for url: https://praktikum.yandex.ru/api/user_api/homework_statuses/?from_date=1622505600
Бот упал с ошибкой: 'NoneType' object has no attribute 'get'
Бот запущен
HTTP error: 401 Client Error: Unauthorized for url: https://praktikum.yandex.ru/api/user_api/homework_statuses/?from_date=1622505600
Бот упал с ошибкой: 'NoneType' object has no attribute 'get'
Бот запущен
HTTP error: 401 Client Error: Unauthorized for url: https://praktikum.yandex.ru/api/user_api/homework_statuses/?from_date=1622505600
Бот упал с ошибкой: 'NoneType' object has no attribute 'get'
Бот запущен
HTTP error: 401 Client Error: Unauthorized for url: https://praktikum.yandex.ru/api/user_api/homework_statuses/?from_date=1622505600
Бот упал с ошибкой: 'NoneType' object has no attribute 'get'
Бот запущен
HTTP error: 401 Client Error: Unauthorized for url: https://praktikum.yandex.ru/api/user_api/homework_statuses/?from_date=1622505600
Бот упал с ошибкой: 'NoneType' object has no attribute 'get'
Бот запущен
HTTP error: 401 Client Error: Unauthorized for url: https://praktikum.yandex.ru/api/user_api/homework_statuses/?from_date=1622505600
Бот упал с ошибкой: 'NoneType' object has no attribute 'get'
Бот запущен
Other error: 'NoneType' object is not subscriptable
Бот упал с ошибкой: 'NoneType' object has no attribute 'get'
Бот запущен
Other error: list index out of range
Бот упал с ошибкой: 'NoneType' object has no attribute 'get'
Бот запущен
Other error: list index out of range
Бот упал с ошибкой: 'NoneType' object has no attribute 'get'
Бот запущен
Бот упал с ошибкой: list index out of range
Бот запущен
Бот запущен
Бот упал с ошибкой: name 'verdict' is not defined
Бот запущен
Бот запущен
Бот запущен
Бот запущен
Бот запущен
Бот запущен
Бот упал с ошибкой: 'NoneType' object is not subscriptable
Бот запущен
Other error: name 'proxies' is not defined
Бот упал с ошибкой: 'NoneType' object has no attribute 'get'
Бот запущен
Other error: HTTPSConnectionPool(host='praktikum.yandex.ru', port=443): Max retries exceeded with url: /api/user_api/homework_statuses/?from_date=1630135238114604358 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fed58190550>: Failed to establish a new connection: [Errno 111] Connection refused')))
Бот упал с ошибкой: 'NoneType' object has no attribute 'get'
Бот запущен
Бот запущен
Бот упал с ошибкой: list index out of range
Бот запущен
Бот упал с ошибкой: list index out of range
Бот запущен
Бот упал с ошибкой: list index out of range
Бот запущен
Бот запущен
Бот запущен
Бот запущен
Бот запущен
Бот запущен
Бот запущен
Бот запущен
Бот запущен
Бот запущен
Бот запущен
Бот запущен
Бот запущен
Бот запущен
Бот запущен
